import React from 'react';
import styles from './Privacy.module.css';

const PrivacyPolicy = () => {
	return (
		<div className={styles.container}>
			<h1 style={{ fontWeight: 700, marginBottom: 16 }}>PRIVACY POLICY</h1>
			<p style={{ marginBottom: 8 }}>Last updated: Sep 01, 2022</p>
			<p>
				This Privacy Policy describes Our policies and procedures on the
				collection, use and disclosure of Your information when You use the
				Service and tells You about Your privacy rights and how the law protects
				You. We use Your Personal data to provide and improve the Service. By
				using the Service, You agree to the collection and use of information in
				accordance with this Privacy Policy.
			</p>
			<br></br>
			<h3>Interpretation</h3>
			<p>
				The words of which the initial letter is capitalized have meanings
				defined under the following conditions. The following definitions shall
				have the same meaning regardless of whether they appear in singular or
				in plural.
			</p>
			<br></br>
			<h3>Definitions</h3>
			<p>
				Account means a unique account created for You to access our Service or
				parts of our Service.
			</p>
			<p>
				{`Organization (referred to as either "the Organization", "We", "Us" or
				"Our" in this Agreement) refers to DeshiDiary.`}
			</p>
			<p>
				Cookies are small files that are placed on Your computer, mobile device
				or any other device by a website, containing the details of Your
				browsing history on that website among its many uses.
			</p>
			<p>
				Device any device that can access the Service such as a computer, a
				cellphone or a digital tablet.
			</p>
			<p>
				Personal Data is any information that relates to an identified or
				identifiable individual.
			</p>
			<p>Service refers to the Website.</p>
			<p>
				Service Provider means any natural or legal person who processes the
				data on behalf of the Organization. It refers to third-party
				organizations or individuals employed by the Organization to facilitate
				the Service, to provide the Service on behalf of the Organization, to
				perform services related to the Service or to assist the Organization in
				analyzing how the Service is used.
			</p>
			<p>
				Usage Data refers to data collected automatically, either generated by
				the use of the Service or from the Service infrastructure itself (for
				example, the duration of a page visit).
			</p>
			<p>
				Website refers to DeshiDiary, accessible from{' '}
				<a href='https://deshidiary.com'>https://deshidiary.com</a>
			</p>
			<p>
				You means the individual accessing or using the Service, or the
				organization, or other legal entity on behalf of which such individual
				is accessing or using the Service, as applicable.
			</p>
			<br></br>
			<h2>Collection and Usage of Data</h2>
			<h3>Types of Data Collected</h3>
			<h4>Personal Data</h4>
			<p>Name</p>
			<p>Email Address</p>
			<p>Phone Number</p>
			<p>Usage Data</p>
			<p>Profile Picture</p>
			<br></br>
			<h3>Usage Data</h3>
			<p>
				Usage Data may include information such as Your {`Device's`} Internet
				Protocol address (e.g. IP address), browser type, browser version, the
				pages of our Service that You visit, the time and date of Your visit,
				the time spent on those pages, unique device identifiers and other
				diagnostic data.
			</p>
			<p>
				When You access the Service by or through a mobile device, We may
				collect certain information automatically, including the type of mobile
				device You use, Your mobile device unique ID, the IP address of Your
				mobile device, Your mobile operating system, the type of mobile Internet
				browser You use, unique device identifiers and other diagnostic data. We
				may also collect information that Your browser sends whenever You visit
				our Service or when You access the Service by or through a mobile
				device.
			</p>
			<h3>Cookies</h3>
			<p>
				We may use Cookies and similar technologies to track the activity on Our
				Service and store certain information. The technologies We use may
				include:
			</p>
			<p>
				{`Cookies or Browser Cookies: A cookie is a small file placed on Your
				Device. You can instruct Your browser to refuse all Cookies or to
				indicate when a Cookie is being sent. However, if You do not accept
				Cookies, You may not be able to use some parts of our Service. Unless
				you have adjusted Your browser setting so that it will refuse Cookies,
				our Service may use Cookies. Cookies can be "Persistent" or "Session"
				Cookies. Persistent Cookies remain on Your personal computer or mobile
				device when You go offline, while Session Cookies are deleted as soon as
				You close Your web browser.`}
			</p>
			<p>
				Purpose: These Cookies allow us to remember choices You make when You
				use the Website. The purpose of these Cookies is to provide You with a
				more personal experience and to avoid You having to re-enter your
				preferences every time You use the Website.
			</p>
			<br></br>
			<h3>Use of Your Personal Data</h3>
			<p>
				The organization may use Personal Data for the following purposes: To
				provide and maintain our Service, including to monitor the usage of our
				Service. To contact You: To contact You by email regarding updates or
				informative communications related to the functionalities, events or
				contracted services, including the security updates, when necessary or
				reasonable for their implementation.
			</p>
			<p>
				To provide You with news, special offers and general information about
				other services and events which we offer unless You have opted not to
				receive such information.
			</p>
			<p>To manage Your requests: To attend and manage Your requests to Us.</p>
			<p>
				For other purposes: We may use your information for other purposes, such
				as data analysis, identifying usage trends, determining the
				effectiveness of our promotional campaigns and to evaluate and improve
				our Service
			</p>
			<br></br>
			<h2>Disclosure of Your Personal Data</h2>
			<h3>Law enforcement</h3>
			<p>
				Under certain circumstances, the organization may be required to
				disclose Your Personal Data if required to do so by law or in response
				to valid requests by public authorities (e.g. a court or a government
				agency).
			</p>
			<h3>Other legal requirements</h3>
			<p>
				The organization may disclose Your Personal Data in the good faith
				belief that such action is necessary to:
			</p>
			<p>Comply with a legal obligation</p>
			<p>Protect and defend the rights or property of the organization</p>
			<p>
				Prevent or investigate possible wrongdoing in connection with the
				Service
			</p>
			<p>Protect the personal safety of Users of the Service or the public</p>
			<p>Protect against legal liability</p>
			<br></br>
			<h3>Links to Other Websites</h3>
			<p>
				Our Service may contain links to other websites that are not operated by
				Us. If You click on a third party link, You will be directed to that
				third {`party's`} site. We strongly advise You to review the Privacy
				Policy of every site You visit.
			</p>
			<p>
				We have no control over and assume no responsibility for the content,
				privacy policies or practices of any third party sites or services.
			</p>
			<h3>Changes to this Privacy Policy</h3>
			<p>
				We may update Our Privacy Policy from time to time. We will notify You
				of any changes by posting the new Privacy Policy on this page.
			</p>
			<p>
				{`	We will let You know via email and/or a prominent notice on Our Service,
				prior to the change becoming effective and update the "Last updated"
				date at the top of this Privacy Policy.`}
			</p>
			<p>
				You are advised to review this Privacy Policy periodically for any
				changes. Changes to this Privacy Policy are effective when they are
				posted on this page.
			</p>
			<br></br>
			<h3>Contact Us</h3>
			<p>
				If you have any questions about this Privacy Policy, You can contact us:
			</p>
			<p>
				By email: <a>support@deshidiary.com</a>
			</p>
		</div>
	);
};

export default PrivacyPolicy;
